drop table if exists t_users CASCADE;
drop table if exists t_user_groups CASCADE;
drop table if exists t_developers CASCADE;
drop table if exists t_projects CASCADE;
drop table if exists t_tasks CASCADE;
drop table if exists t_skills CASCADE;
drop table if exists t_developers_tasks CASCADE;
drop table if exists t_developers_skills CASCADE;
drop table if exists t_tasks_skills CASCADE;
